run tests:
  stage: test
  image: python:3
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - coverage run --source statkit -m unittest discover test
    - coverage report
    - coverage xml
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    reports:
      cobertura: coverage.xml

pages:
  image: python:3
  stage: deploy
  script:
  - pip3 install pdoc3
  - pip3 install -r requirements.txt
  - mkdir public
  - pdoc --config latex_math=True --html --output-dir public statkit
  - mv public/statkit/* public/ && rmdir public/statkit/
  artifacts:
    paths:
    - public
  only:
  - main
